version: '3.8'

services:
  resource-management:
    build: .
    container_name: resource_management_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - app_data:/app/data
    restart: unless-stopped

volumes:
  app_data:
